mobxjs/mobx.dart

lib/src/core/action.dart, lib/src/core/base_types.dart, lib/src/core/computed.dart, lib/src/core/observable.dart, lib/src/interceptable.dart, lib/src/listenable.dart, test/intercept_test.dart
- interceptors for observable values
=> - observe() for computed

lib/src/core/observable.dart, lib/src/listenable.dart, test/all.dart, test/listenable_test.dart
Same kind of change I did for Interceptable
=> Use composition for Listenable

lib/mobx.dart, lib/src/api/action.dart, lib/src/api/context.dart, lib/src/api/observable.dart, lib/src/api/reaction.dart, lib/src/core.dart, lib/src/core/action.dart, lib/src/core/atom.dart, lib/src/core/computed.dart, lib/src/core/context.dart, lib/src/core/derivation.dart, lib/src/core/observable.dart, lib/src/core/reaction.dart, lib/src/core/reaction_helper.dart, lib/src/interceptable.dart, lib/src/listenable.dart, test/action_test.dart, test/derivation_tracker_test.dart, test/intercept_test.dart, test/listenable_test.dart, test/observable_test.dart, test/reaction_test.dart, test/shared_mocks.dart, test/when_test.dart
`src/core.dart` now combines all files in `src/core/` into a single module.
Next step is refactoring and making things private
=> Combine core using partial files

flutter_mobx/example/lib/todos/todo_widgets.dart, flutter_mobx/example/lib/todos/todos.dart
Hi @pavanpodila 
Please check the code.
I did what you taught me in Gitter's chat.
=> fix: Disable button Remove Completed, when the completed task is occult.

mobx/lib/src/api/observable_collections.dart, mobx/lib/src/api/observable_collections/observable_set.dart, mobx/test/all.dart, mobx/test/observable_set_test.dart
=> Add ObservableSet

mobx/lib/mobx.dart, mobx/lib/src/api/observable_collections/observable_list.dart
Also renamed `ListChangeNotification` to `ListChange` to match the other collections
=> Export all public items from collections

analysis_options.yaml, mobx/lib/src/api/observable_collections/observable_list.dart, mobx/lib/src/api/observable_collections/observable_map.dart, mobx/lib/src/api/observable_collections/observable_set.dart, mobx/lib/src/core/action.dart, mobx/lib/src/core/atom.dart, mobx/lib/src/core/computed.dart, mobx/lib/src/core/context.dart, mobx/lib/src/core/observable.dart, mobx/test/action_controller_test.dart, mobx/test/action_test.dart, mobx/test/computed_test.dart, mobx/test/context_test.dart, mobx/test/observable_future_test.dart, mobx/test/shared_mocks.dart, mobx/test/when_test.dart
- Checks if an observable is being mutated inside a computed function
- Will be adding support for `enforceActions` (#87)
=> Enforce actions

mobx/test/observable_stream_test.dart
More to come, I need to do some refactoring on ObservableFuture first.
=> Add tests for stream combinators

flutter_mobx/lib/src/observer.dart, mobx/lib/src/api/annotations.dart, mobx/lib/src/api/reaction.dart
I added some doc comments to `Observer` and the annotations found in the [Concepts](https://mobx-dart.netlify.com/concepts) section of the online tutorial. I'm somewhat new to MobX so let me know if anything is off.
=> Small documentation improvements

flutter_mobx/example/lib/main.dart, flutter_mobx/example/lib/todos/todo_widgets.dart, flutter_mobx/example/test/widget_test.dart, flutter_mobx/pubspec.yaml, mobx/README.md, mobx_codegen/pubspec.yaml
We have `dependencies` that are pointing to local paths. This is causing problems while publishing to pub. Fixing them
=> fix the pubspec versions

README.md
Not that it makes much difference, but I think it might be clear :)
=> Fix small typo (I believe) in readme

tool/intellij/MobX.xml, tool/intellij/Mobx.xml, tool/intellij/README.md
=> add store live templates and readme for live templates

.idea/workspace.xml, flutter_mobx/lib/src/observer.dart, flutter_mobx/test/flutter_mobx_test.dart
=> rethrow exceptions occurring inside the `Observer`

docs/src/examples/form/index.mdx
Hi Pawan,
I've added validators link to form example. Could you please review
=> added validators link to form example

docs/src/core-concepts.mdx
Hi Pawan,
I've added the link of the complete code base present in git repository. Could you please review
=> added the link of the complete code base present in git repository

docs/src/examples/form/index.mdx
Hi Pawan,
I've added space in line. Could you please review
=> added space

docs/src/community.md
I've changed domains (though the old one should redirect). Paul's article no longer exists on his site so added a link to the video. Also removed the periods that were being used inconsistently
=> Update community page

mobx/lib/mobx.dart, mobx/lib/src/api/annotations.dart
We're splitting this out from the codegen work so that we can get an
alpha package published, and have the codegen package depend on that.
I selected `master` as the merge target, but feel free to change it to 
something more appropriate.
=> Add the @store annotation

mobx_codegen/lib/src/mobx_codegen_base.dart
While prepping support for adding `@store` annotation support, I saw an
opportunity to generalize how we match on suitable base class / mixed
class pairs.
The insight was that the two paths through the match logic (type 
parameterized vs not) were essentially the same, if you consider
a unparameterized type the same as an parameterized type with zero type 
params.
I also added a bunch of comments, which should help the next person
digest it.
Related to #225
=> Simplify class matching logic in codegen

docs/src/community.md, docs/src/core-concepts.mdx, mobx/README.md
I also removed a period that i missed in #243 and updated the info about the MobX quick start guide to say nearly all of the concepts are applicable instead of having it say it's 100% applicable given deep observability isn't possible
=> Add info on lack of deep observability

mobx_codegen/lib/src/template/constructor_override.dart, mobx_codegen/test/data/valid_annotated_store_output.dart
And updated the test to reflect the fix.
Related to issue reported by @hramnathnayak in #268
=> Fix @store super call to referenced named constructors

mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/template/params.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/valid_input.dart, mobx_codegen/test/data/valid_output.dart, mobx_codegen/test/data/valid_store_with_ui_types_input.dart, mobx_codegen/test/data/valid_store_with_ui_types_output.dart
=> Inherit @required annotations in overidden methods

mobx/lib/src/api/observable_collections/observable_set.dart, mobx/test/observable_set_test.dart
This mimics the other Observable collections.
=> Include a set reference in ObservableSet change notifications

mobx_codegen/lib/src/template/store_file.dart
=> Prevent output if no stores were generated

docs/src/guides/organizing-stores.mdx
Missed that I incorrectly used the square brackets for part of the text
=> close off brackets correctly  in organising stores page

docs/src/development/release.mdx, flutter_mobx/lib/flutter_mobx.dart, flutter_mobx/lib/src/observer.dart, flutter_mobx/test/flutter_mobx_test.dart, mobx/lib/mobx.dart, mobx/test/bug_related_test.dart, mobx/test/observable_future_test.dart, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/test/mobx_codegen_test.dart, tool/expose_version.dart
This is an attempt to automate the version synchronization between the pubspecs and the library files.
Closes #213
=> Expose versions

mobx/lib/mobx.dart, mobx/lib/src/api/extensions.dart, mobx/lib/src/api/extensions/observable_future_extension.dart, mobx/lib/src/api/extensions/observable_list_extension.dart, mobx/lib/src/api/extensions/observable_map_extension.dart, mobx/lib/src/api/extensions/observable_set_extension.dart, mobx/lib/src/api/extensions/observable_stream_extension.dart, mobx/pubspec.yaml, mobx/test/extensions/observable_future_extension_test.dart, mobx/test/extensions/observable_list_extension_test.dart, mobx/test/extensions/observable_map_extension_test.dart, mobx/test/extensions/observable_set_extension_test.dart, mobx/test/extensions/observable_stream_extension_test.dart
```dart
ObservableStream output = stream.asObservable();
```
instead
```dart
ObservableStream output = ObservableStream(stream);
```
=> added ObservableStream, ObservableFuture and Collections extension #345

flutter_mobx/lib/src/observer.dart
Mostly just a rewrap to 80 char line length across the board, and removal of a couple superfluous comments.
=> Clean up comments

README.md, mobx/README.md, translation/pt-BR/README.md
Start translation to pt-BR 
[x] start folder structure
[x] translate to pt-BR
=> Translate documentation to pt-BR #317

tool/circle_run.sh
This comes in handy for bug reports.
=> Add Dart version echo to CI

docs/src/examples/form/index.mdx, docs/src/guides/when-does-mobx-react.mdx
I changed URL from localhost to correct GitHub docs
=> Remove localhost references in docs

mobx/lib/src/api/observable_collections/observable_map.dart, mobx/test/observable_map_test.dart
=> Fix ObservableMap not adding null values

mobx/CHANGELOG.md, mobx/lib/mobx.dart, mobx/lib/src/api/annotations.dart, mobx/pubspec.yaml, mobx/test/annotations_test.dart
Split of "Add generation of toString method when @tostring annotation is
used #414 " in order to deal properly with inter dependencies
=> Add StoreConfig annotation in mobx

docs/src/getting-started/index.mdx
=> Fix a typo

docs/src/examples/connectivity/index.mdx, mobx/lib/src/api/reaction.dart
=> Update delay in docs

mobx_codegen/lib/src/template/store_file.dart
unnecessary_brace_in_string_interps added for ignorance
=> Template warning addition

docs/src/community.mdx
First of all, thanks for all the hard work on this package!
I would like to share an article I've written that helps address the issue on #200.
More on:
https://codedash.dev/keeping-it-simple-integrate-graphql-mobx-to-your-flutter-app/
Hope this helps.
- Closes #200
=> docs: Add redirect to GraphQL + MobX blog. Closes #200

mobx_codegen/lib/src/template/computed.dart, mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/template/params.dart, mobx_codegen/lib/src/type_names.dart, mobx_codegen/test/data/valid_generic_store_input.dart, mobx_codegen/test/data/valid_generic_store_output.dart, mobx_codegen/test/data/valid_import_prefixed_input.dart, mobx_codegen/test/data/valid_import_prefixed_output.dart, mobx_codegen/test/data/valid_input.dart, mobx_codegen/test/data/valid_input_annotation_store_config_has_to_string.dart, mobx_codegen/test/data/valid_output.dart, mobx_codegen/test/data/valid_output_annotation_store_config_has_to_string.dart, mobx_codegen/test/templates_test.dart, mobx_codegen/test/test_utils.dart
Same code as https://github.com/mobxjs/mobx.dart/pull/631
=> Support NNBD (Null safety) for generated code of mobx_codegen (new)

mobx/lib/src/api/observable_collections/observable_map.dart, mobx/lib/src/core/reaction_helper.dart
Closes https://github.com/mobxjs/mobx.dart/issues/639
Closes https://github.com/mobxjs/mobx.dart/issues/640
=> Make ObservableMap consistent with Map and fix bug of null in reaction()

README.md, docs/docs/api/observable.mdx, mobx/README.md
Also updated the summary to simplify searching for `@foo_bar`. Let me know if you don't want this behavior.
=> Adds @readonly to the docs

docs/docs/community.mdx
- Closes #685 
- Change the deprecated docs to the new URL
=> [docs] Update deprecated website for an article

docs/docs/guides/organizing-stores.mdx
from `@observbale` to `@observable`
=> docs: fix typo

flutter_mobx/lib/src/observer_widget_mixin.dart, flutter_mobx/lib/src/stateful_observer_widget.dart, flutter_mobx/test/flutter_mobx_test.dart
This PR fixes linting problems in `flutter_mobx` which is interfering in another PRs.
=> ci: fix pipeline

mobx/lib/src/api/observable_collections/observable_map.dart
Not sure why I added that redundant bracket...
=> Remove redundant brackets

flutter_mobx/lib/src/observer_widget_mixin.dart
should not break anything imho
=> Change from `late` to `late final` to make the code a bit stronger

flutter_mobx/lib/src/observer_widget_mixin.dart, flutter_mobx/test/flutter_mobx_test.dart
=> Routine PR

README.md, docs/docs/api/reaction.mdx, docs/docs/core-concepts.mdx, mobx/README.md, translation/pt-BR/README.md, translation/zh-CN/README.md
Thank you so much for MobX, I absolutely love it and really appreciate all the hard work that has gone into creating it.
While reading the docs I noticed that we are assigning the result of Observable into a String, and that just won't compile. So I fixed that by replacing "String" with "final"
=> result of Observable is not a String, but an Observable

flutter_mobx/CHANGELOG.md, flutter_mobx/lib/flutter_mobx.dart, flutter_mobx/lib/src/observer.dart, flutter_mobx/lib/src/observer_widget_mixin.dart, flutter_mobx/lib/src/stateless_observer_widget.dart, flutter_mobx/pubspec.yaml, flutter_mobx/test/flutter_mobx_test.dart, flutter_mobx/test/helpers.dart, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/builder.dart, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/store_class_visitor.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/store_class_visitor_test.dart
Closes #777
Closes #776
Closes #692
Closes #779
Closes #780
=> Routine PR (2022.03.18)

flutter_mobx/lib/src/observer_widget_mixin.dart, mobx_codegen/pubspec.yaml
=> migrate to flutter 3.0 by removing no longer needed null checks

mobx/CHANGELOG.md, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/pubspec.yaml
resolve https://github.com/mobxjs/mobx.dart/issues/803
Signed-off-by: Minsu Lee <amond@amond.net>
=> Upgrading `mobx` to `2.0.7`

docs/docs/api/observable.mdx
=> Fix typo in observable.mdx

mobx_codegen/lib/src/type_names.dart, tool/coverage.sh
If the test fails, github action should fail.
https://github.com/mobxjs/mobx.dart/pull/784 has failed tests, but [check](https://github.com/mobxjs/mobx.dart/runs/6815659674?check_suite_focus=true) succeeded.
---
=> ci: if the test fails, github action should fail.

docs/docs/api/observable.mdx
Added Documentation regarding discussion #851
=> docs: added #851 discussions on ObservableList

mobx/analysis_options.yaml, mobx/lib/version.dart, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/store_class_visitor.dart, mobx_codegen/lib/src/template/action.dart, mobx_codegen/lib/src/template/annotations_generator_mixin.dart, mobx_codegen/lib/src/template/async_action.dart, mobx_codegen/lib/src/template/observable_future.dart, mobx_codegen/lib/src/template/observable_stream.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/annotations_test_class_input.dart, mobx_codegen/test/data/annotations_test_class_output.dart, mobx_codegen/test/generator_usage_test.g.dart, mobx_codegen/test/mobx_codegen_test.dart, mobx_codegen/test/nested_store.g.dart, mobx_codegen/test/store_with_custom_context.g.dart, mobx_codegen/test/templates_test.dart, mobx_examples/lib/form/form_store.dart
Adds support for annotations `@protected`, `@visibleForTesting` and `@visibleForOverriding` for actions, observables futures and observables stream.
Closes #899
=> feat: Adds support for annotations

flutter_mobx/CHANGELOG.md, flutter_mobx/lib/flutter_mobx.dart, flutter_mobx/lib/version.dart, flutter_mobx/pubspec.yaml
=> refactor: export `MultiReactionBuilder` from `flutter_mobx.dart`

mobx/CHANGELOG.md, mobx/lib/src/core/observable.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/observable_test.dart
Fix Observable.value setter when class with operator ==(covariant) is used as a value
=> fix: Observable.value setter (covariant)

README.md, mobx_codegen/example/README.md, translation/ja-JP/README.md, translation/ko-KR/README.md, translation/pt-BR/README.md, translation/zh-CN/README.md
=> [Fix] Broken Links

.github/workflows/build.yml
It often happens that tests fail when `dart` versions are updated.  Perform CI periodically so that we can quickly fix them when that happens.
---
=> ci: run the CI every day at 10AM

docs/docs/api/observable.mdx, docs/docs/api/observers.mdx
Hi, I found some time to add a doc items you asked here https://github.com/mobxjs/mobx.dart/pull/958#pullrequestreview-1747396331
I've also added a reference for `.obs()` and `.toggle()` introduced in 2.0.7.
=> [docs] obs(), toggle()
