lib/src/api/reaction.dart, lib/src/api/reaction_helper.dart, lib/src/utils.dart, test/reaction_test.dart
Mirrors are not supported in Flutter or recommended on the web platform, as reflection makes tree shaking the code impossible. (see https://www.dartlang.org/articles/server/reflection-with-mirrors).
I just removed the "overload" of reaction, as the parameter can easily be ignored by using `_` as the name.
=> Remove dart:mirrors usage

lib/src/api/action.dart, lib/src/api/context.dart, lib/src/api/observable.dart, lib/src/api/reaction.dart, lib/src/api/reaction_helper.dart, lib/src/core/action.dart, lib/src/core/atom.dart, lib/src/core/computed.dart, lib/src/core/context.dart, lib/src/core/derivation.dart, lib/src/core/observable.dart, lib/src/core/reaction.dart, lib/src/interceptable.dart, lib/src/listenable.dart, pubspec.yaml, test/action_test.dart, test/computed_test.dart, test/observable_test.dart, test/reaction_test.dart, test/shared_mocks.dart
Made the ReactiveContext an explicit argument for classes that need it.
Builder functions provide the global context if it's not provided for them as an optional named argument.
I tried to implement the Zone local value for the context, but it did not work properly with tests. I don't know why exactly. It can be implemented in the future by changing `mobxContext` global to a getter that finds the current Zones context.
=> Inject ReactiveContext as constructor argument

lib/src/core/observable.dart, lib/src/interceptable.dart, lib/src/utils.dart, test/autorun_test.dart, test/intercept_test.dart, test/when_test.dart
The Interceptable made too many things public and the code was a bit javascripty, so I decided to refactor it a bit. Tried to add all functions into the mixin, but then all the mixin methods would be public in ObservableValue. I think composition made it cleaner.
I'll do the same thing to Listenable if this looks ok to you @pavanpodila
=> Make Interceptable use composition

example/lib/src/generator_example.dart, example/lib/src/generator_example.g.dart, example/test/generator_example_test.dart, flutter_mobx/example/lib/counter.dart, flutter_mobx/example/lib/todos.dart, mobx/lib/mobx.dart, mobx/lib/src/api/annotations.dart, mobx_codegen/build.yaml, mobx_codegen/lib/builder.dart, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/template/action.dart, mobx_codegen/lib/src/template/comma_list.dart, mobx_codegen/lib/src/template/computed.dart, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/lib/src/template/rows.dart, mobx_codegen/lib/src/template/store.dart, mobx_codegen/lib/src/template/util.dart, mobx_codegen/test/all.dart, mobx_codegen/test/mobx_codegen_test.dart, mobx_codegen/test/templates_test.dart
Moved templates into their own files.
Changed the code generator to generate a mixin, this allows user defined constructors and inheritance of stores.
=> Generate a mixin with code generator

mobx_codegen/lib/src/errors.dart, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/template/store.dart, mobx_codegen/test/all.dart, mobx_codegen/test/errors_test.dart, mobx_codegen/test/mobx_codegen_test.dart
Added some validations for the codegen.
final/static `@observable` fields, and static/async `@action` methods generate a warning in the console and prevent code generation.
Needs more in the future, but this is a start.
=> Add checks and errors for codegen

flutter_mobx/example/lib/todos/todos.dart
`itemBuilder` should be pulling todos from `list.visibleTodos`, not `list.todos`
=> Fixed incorrect building of todo items in example

flutter_mobx/lib/flutter_mobx.dart, flutter_mobx/lib/src/observer.dart, flutter_mobx/pubspec.yaml, flutter_mobx/test/flutter_mobx_test.dart, mobx/lib/src/core/reaction.dart, mobx/pubspec.yaml, mobx/test/reaction_test.dart
This will check the builder function and assert if no observables are detected. I ran into this issue a few days back and took quite some time to figure out that there were no observables being tracked inside! I think this is a good sanity check to have.
=> Check observer

mobx_codegen/example/lib/src/generator_example.dart, mobx_codegen/example/lib/src/generator_example.g.dart, mobx_codegen/example/pubspec.yaml, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/template/params.dart, mobx_codegen/lib/src/template/store.dart, mobx_codegen/lib/src/template/util.dart, mobx_codegen/test/mobx_codegen_test.dart, mobx_codegen/test/templates_test.dart
Support codegen for generic stores:
```dart
class Item<A> = _Item<A> with _$Item<A>;
abstract class _Item<T> implements Store {
@observable
T value;
}
```
Fixes #118
=> Codegen support for generic stores

mobx/lib/src/core/action.dart, mobx/test/action_controller_test.dart
`ActionController` used to throw when both `context` and `name` were omitted. 
This PR fixes the issue
=> fix ActionController throwing null exception with null context/name

mobx/lib/src/api/observable_collections/observable_list.dart, mobx/test/observable_list_test.dart
This should fix #193. As part of this, it looked like the `addAll` and `replaceRange` had similar issues so made some changes there. Added in some extra tests to improve the test coverage as well
=> fix observable list notifications and improve test coverage

mobx/CHANGELOG.md, mobx/example/lib/counter.g.dart, mobx/example/lib/todos.g.dart, mobx/lib/src/api/async/observable_future.dart, mobx/lib/src/api/observable_collections/observable_list.dart, mobx/lib/src/api/observable_collections/observable_map.dart, mobx/lib/src/api/observable_collections/observable_set.dart, mobx/lib/src/core/context.dart, mobx/pubspec.yaml, mobx/test/context_test.dart, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/generator_usage_test.g.dart, mobx_codegen/test/mobx_codegen_test.dart, mobx_codegen/test/nested_store.g.dart, mobx_codegen/test/templates_test.dart, mobx_examples/lib/counter/counter.g.dart, mobx_examples/lib/form/form_store.dart, mobx_examples/lib/form/form_store.g.dart, mobx_examples/lib/form/form_widgets.dart, mobx_examples/lib/github/github_store.g.dart, mobx_examples/lib/hackernews/news_store.g.dart, mobx_examples/lib/multi_counter/multi_counter_store.g.dart, mobx_examples/lib/todos/todo.g.dart, mobx_examples/lib/todos/todo_list.g.dart
Addresses some comments raised in #206 around using the conditional action wrapping even for collection methods. This makes it easier to use collection modifiers safely from the get go
=> Adding conditional action wrappers for collection mutating methods

docs/src/getting-started/index.mdx
Hi Pawan,
I've added folder name in add store section. Could you please review it
=> added folder location in add store section

mobx/lib/src/api/reaction.dart, mobx/lib/src/core.dart, mobx/lib/src/core/observable.dart, mobx/lib/src/core/reaction_helper.dart, mobx/test/observe_test.dart, mobx/test/reaction_test.dart
I'm already using this feature in my project but I'd like to get some feedback on this, if I'm doing it right I'd also like to contribute more with docs & tests. 😄
Add the possibility to override equality comparator function in reactions. This feature is already present in the JavaScript version, detailed here: https://mobx.js.org/refguide/reaction.html
The problem originally was that I have 2 types which I don't have control of, to override the `compareTo` or `==` operator, but they are constantly changing in my app and I need to react on changes of them even if they are just reassigned with the same value.
What do you think, is this feature a step towards the right direction or should mobx encourage people defining their own wrappers and equality?
EDIT: Update after some investigation I …
=> Reaction comparator

docs/src/guides/organizing-stores.mdx, mobx_examples/lib/examples.dart, mobx_examples/lib/form/form_widgets.dart, mobx_examples/lib/github/github_widgets.dart, mobx_examples/lib/hackernews/news_widgets.dart, mobx_examples/lib/main.dart, mobx_examples/lib/multi_counter/multi_counter_widgets.dart, mobx_examples/lib/random_stream/random_widgets.dart, mobx_examples/lib/settings/preferences_service.dart, mobx_examples/lib/settings/settings_store.dart, mobx_examples/lib/settings/settings_store.g.dart, mobx_examples/lib/settings/settings_widgets.dart, mobx_examples/lib/todos/todo_list.dart, mobx_examples/lib/todos/todo_widgets.dart, mobx_examples/pubspec.yaml, mobx_examples/test/widget_test.dart
- Added an example that for demonstrating using the ProxyProvider and Consumer widgets. Updated relevant docs as well
- Updated code in example to use relative imports (as per https://dart.dev/guides/language/effective-dart/usage#prefer-relative-paths-when-importing-libraries-within-your-own-packages-lib-directory). Can revert if there's a reason I may have missed on why package imports had been used
- Note that I updated the wording in the organizing stores page around the Provider API, as I believe it's more correct to say that it deals with constructing and disposing objects
=> Add settings example with ProxyProvider

mobx/lib/src/api/observable_collections/observable_map.dart
oldValue was only being set in certain conditions, which prevented the equality check from having the desired effect.
=> Fix change reporting in ObservableMap.[]=

mobx_codegen/lib/src/errors.dart, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/lib/src/template/store.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/invalid_store_declaration.dart, mobx_codegen/test/data/invalid_store_declaration_output.txt, mobx_codegen/test/data/valid_annotated_store_input.dart, mobx_codegen/test/data/valid_annotated_store_output.dart, mobx_codegen/test/data/valid_generic_annotated_store_input.dart, mobx_codegen/test/data/valid_generic_annotated_store_output.dart, mobx_codegen/test/invalid_annotations_test.dart, mobx_codegen/test/mobx_codegen_test.dart, mobx_codegen/test/templates_test.dart
Adds code generation support for `@store` annotation syntax.
If a private class annotated with `@store` is encountered, we now generate its public, MobX counterpart.
Example:
```dart
@store
class _User {
@observable
int value;
}
```
Produces:
```dart
class User extends _User {
final _$valueAtom = Atom(name: '_User.value');
@override
int get value {
_$valueAtom.context.enforceReadPolicy(_$valueAtom);
_$valueAtom.reportObserved();
return super.value;
}
@override
set value(int value) {
_$valueAtom.context.conditionallyRunInAction(() {
super.value = value;
_$valueAtom.reportChanged();
}, _$valueAtom, name: '${_$valueAtom.name}_set');
}
}'
```
We do not remove support for the existing, mixin-style syntax.
=> Store annotation codegen

mobx_codegen/lib/src/errors.dart, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/template/constructor_override.dart, mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/lib/src/template/store.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/invalid_store_declaration.dart, mobx_codegen/test/data/invalid_store_declaration_output.txt, mobx_codegen/test/data/valid_annotated_store_input.dart, mobx_codegen/test/data/valid_annotated_store_output.dart, mobx_codegen/test/data/valid_generic_annotated_store_input.dart, mobx_codegen/test/data/valid_generic_annotated_store_output.dart, mobx_codegen/test/invalid_annotations_test.dart, mobx_codegen/test/mobx_codegen_test.dart, mobx_codegen/test/templates_test.dart
There are still two remaining tasks:
=> Add code generation support for the @store annotation

mobx_examples/lib/main.dart
Was looking at an example app that one of the members of the Flutter team and found out that the main function can be made to return a `Future`. This should allow us to having an async void function and remove the need to suppress the warning
=> make main function in examples return a future

mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/template/store.dart, mobx_codegen/lib/src/template/store_file.dart
In this PR we introduce a new template representing a file containing one or more stores. This template includes a single top-level `ignore_for_file` directive.
Fixes #270
=> Output a single ignore_for_file per store file

mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/template/util.dart, mobx_codegen/lib/src/type_names.dart, mobx_codegen/test/data/valid_annotated_store_input.dart, mobx_codegen/test/data/valid_annotated_store_output.dart, mobx_codegen/test/data/valid_annotated_store_referencing_store_input.dart, mobx_codegen/test/data/valid_annotated_store_referencing_store_output.dart, mobx_codegen/test/data/valid_store_with_ui_types_input.dart, mobx_codegen/test/data/valid_store_with_ui_types_output.dart, mobx_codegen/test/mobx_codegen_test.dart
If the analyzer is unable to resolve a type, it reports that the type is
"dynamic", and our codegen writes it out way. This situation is
particularly noticeable because the build package's analyzer draws from
a pre-computed analysis summary that does not include dart:ui.
The recent work on annotated stores demonstrates a similar and related
problem, where we'd like to reference generated types in our store
definitions, but because the analyzer doesn't know about types that have
not yet been generated, dynamics litter the generated code.
This PR explores an approach where we output types to generated code
as they were written in the input instead of relying on the analyzer's
interpretation. If we encounter a type that the analyzer reports as
dynamic, we look up the element's AST node, and …
=> Add support for codegen of "unknown" type names

flutter_mobx_forms/lib/src/field_state.dart
Because assert(!_isValidating) is asserting negate of null which is illegal.
=> _isValidating can't be null

flutter_mobx/lib/src/observer.dart, flutter_mobx/test/flutter_mobx_test.dart
Errors that occur internal to the setState() call are now reported via FlutterError.reportError so they don't go unnoticed by the user.
=> Report errors that occur during Observer.setState

mobx_codegen/lib/src/type_names.dart, mobx_codegen/test/data/valid_annotated_store_referencing_store_input.dart, mobx_codegen/test/data/valid_annotated_store_referencing_store_output.dart, mobx_codegen/test/data/valid_store_with_ui_types_input.dart, mobx_codegen/test/data/valid_store_with_ui_types_output.dart
Turns out that a `NormalFormalParameter` is not always the node that we find when searching for a `ParameterElement`'s counterpart in the AST. If a `DefaultFormalParameter` is discovered, we will now traverse to the `SimpleFormalParameter` containing the type name.
=> Fix a case where an unknown parameter type is missed

mobx_codegen/lib/src/type_names.dart, mobx_codegen/test/data/valid_input.dart, mobx_codegen/test/data/valid_output.dart
A parameter without a type annotation was having its type generated as "null". This corrects the situation by handling the null case in the parameter type name finder.
Fixes #298
=> Support parameters without type annotations

mobx/lib/src/api/async/observable_future.dart, mobx/lib/src/api/async/observable_stream.dart, mobx/lib/src/core.dart, mobx/lib/src/core/computed.dart, mobx/lib/src/core/observable.dart, mobx/lib/src/core/observable_value.dart, mobx/test/observable_value_test.dart
This allows to work with observable classes(`Observable`, `Computed`, `ObservableFuture`, `ObservableStream`) through a common interface.
Fixes #301
=> Add ObservableValue class

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/store_class_visitor.dart, mobx_codegen/lib/src/type_names.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/valid_annotated_store_referencing_store_input.dart, mobx_codegen/test/data/valid_annotated_store_referencing_store_output.dart, mobx_codegen/test/data/valid_import_prefixed_input.dart, mobx_codegen/test/data/valid_import_prefixed_output.dart, mobx_codegen/test/mobx_codegen_test.dart, mobx_examples/pubspec.yaml
Allow a version range for the analyzer package so that downstream packages can take advantage of the newer build_resolver package. Of note, the newer build_resolver resolves dart:ui types.
This also changes the supertype check for mixin-style stores to use the TypeSystem class. The previously used method is deprecated in the latest analyzer.
Updating the analyzer had the side-effect of not outputting prefixed types (like ui.Color) because they are no longer unknown, but the I've updated the type name finders so they always ask the AST as a workaround.
Fixes #130
=> Upgrade the analyzer to support a range of versions

mobx_examples/lib/connectivity/connectivity_store.dart, mobx_examples/lib/connectivity/connectivity_store.g.dart, mobx_examples/lib/connectivity/connectivity_widgets.dart, mobx_examples/lib/examples.dart, mobx_examples/lib/main.dart, mobx_examples/pubspec.yaml
added a new example as discussed in #316
=> add connectivity example that demonstrates using a reaction

flutter_mobx/lib/src/observer.dart
Errors have attached stack traces as well, so we might as well be showing them.
=> Display stack traces with all caught errors

mobx_codegen/test/test_utils.dart
Previously the generator would fail with 'Error running StoreGenerator'
in test situations, adding overhead to figuring out the source of
errors.
Closes #343
=> Print full error details in test scenarios

mobx_codegen/test/test_utils.dart
This was getting a little noisy in the general case, because our application-level validation logs to SEVERE.
=> Suppress test error logging in absence of exception

.gitignore
This file is generated as a result of a `pub run test_coverage`, and is unneeded.
=> Add generated test coverage badge to gitignore

mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/pubspec.yaml
Two APIs we depend on become deprecrated in the 0.39.x series. I've ignored them for now, and filed
https://github.com/mobxjs/mobx.dart/issues/354 to add support as we remove support for older `analyzer` versions.
Fixes #341
=> Add support for analyzer 0.39.x

flutter_mobx/lib/src/observer.dart, flutter_mobx/test/flutter_mobx_test.dart
Having been moved into a getName() call, the use of stack traces failed to serve its purpose of pointing to a location in user source for easier debugging.
Determination of the stack frame has also been improved to search for the first non-constructor, in order to support subclasses of Observable. This functionality has been tested in the browser and VM.
Fixes #361
=> Correct Observer debug name to point to constructing frame

flutter_mobx/test/flutter_mobx_test.dart
Const constructors are run during the build, not at runtime, which means using them in tests prevents code coverage from hitting their lines.
=> Remove const instance for better coverage

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/pubspec.yaml
Analyzer versions prior to 0.38.5 were failing to resolve certain dart:core and dart:async types, and as such they were being written to generated code as dynamic.
Fixes #367
=> Upgrade our minimum analyzer dependency to 0.38.5

flutter_mobx/pubspec.yaml, mobx/pubspec.yaml, mobx_codegen/pubspec.yaml
I forked test_coverage to https://github.com/shyndman/test-coverage and added additional logging to hopefully catch the source of our CircleCI problems (an example of which is here: https://app.circleci.com/jobs/github/mobxjs/mobx.dart/2178).
I was unable to reproduce the failure after repeated re-running of the pipeline, but hopefully we should see it rear its ugly head sometime soon.
Related to #356
=> Use forked test_coverage for debugging failure issues

mobx_codegen/lib/src/type_names.dart
The analyzer 0.39.3 update was causing our latest builds to break, because of a new deprecation to `DartType.displayName`.
I updated #354 as a reminder to remove it when we upgrade our dependencies.
=> Ignore another analyzer deprecation

docs/src/api/reaction.mdx, docs/src/core-concepts.mdx, mobx/README.md, mobx/lib/src/api/reaction.dart, mobx/lib/src/core/reaction_helper.dart, mobx/test/autorun_test.dart, mobx/test/reaction_test.dart
Noticed that the argument in `reaction` was named as `predicate` when it doesn't return a boolean value. Changed this to `fn` though we may want to change this something else. Alternatives I can think of are `trackingFunction`/`trackingFn` or `dataFunction`/`dataFn`
Sidenote: suggest agreeing on a standard in the API docs. I noticed there are cases where functions are referred to as `<function>` and other places use `<function>()`. I would suggest the former and it's also the approach used in the Flutter docs
=> Fix naming of tracking function argument in reaction

mobx_codegen/lib/src/type_names.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/valid_generic_store_input.dart, mobx_codegen/test/data/valid_generic_store_output.dart, mobx_codegen/test/data/valid_import_prefixed_input.dart, mobx_codegen/test/data/valid_import_prefixed_output.dart
There were a number of bugs with the previous implementation of the `LibraryScopedNameFinder`. This resolves them, as well as ensures that a single code path is followed whether or not the analyzed source code contains named imports, reducing the potential for future bugs.
The following bugs have been corrected when using named imports:
* Missing type arguments on classes
* Missing type arguments on function typedefs
* Missing prefixes from imported typedefs
* Missing prefixes from implicit type argument bounds
Fixes #367
=> Fix @observable generic types when using import aliases

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/pubspec.yaml
This resolves the `dart:ui` type resolution problems we've been seeing with some versions of Flutter.
Fixes #381
=> Upgrade build_resolvers to 1.3.2

mobx/lib/src/api/observable_collections/observable_map.dart
The documentation incorrectly stated that this class is the observable counterpart to the standard dart List interface while it is the counterpart to the Map interface.
=> Corrected ObservableMap documentation

README.md
The netlify deploy is on mobx.netlify.com; there were two links to mobx-dart still in the readme.
=> Fixes two links to mobx-dart on netlify

docs/src/core-concepts.mdx
I think that in the example of Computed Observables the class Contact as part with name "contact.g.dart" and not "counter.g.dart".
Maybe it's a typo from the previuos example.
=> Fix a typo in Computed Observables section

.github/workflows/build.yml, .gitignore, mobx/pubspec.yaml, mobx/test/all_tests.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/all_tests.dart, tool/coverage.sh
This removes the dependency on `test_coverage` and relies on the base package `coverage` to all the work of collecting coverage. This appears to be more reliable on CI.
=> Simpler coverage

mobx/test/action_controller_test.dart, mobx/test/action_test.dart, mobx/test/annotations_test.dart, mobx/test/async_action_test.dart, mobx/test/autorun_test.dart, mobx/test/bug_related_test.dart, mobx/test/computed_test.dart, mobx/test/context_test.dart, mobx/test/exceptions_test.dart, mobx/test/extensions/observable_future_extension_test.dart, mobx/test/extensions/observable_list_extension_test.dart, mobx/test/extensions/observable_map_extension_test.dart, mobx/test/extensions/observable_set_extension_test.dart, mobx/test/extensions/observable_stream_extension_test.dart, mobx/test/intercept_test.dart, mobx/test/listenable_test.dart, mobx/test/observable_future_test.dart, mobx/test/observable_list_test.dart, mobx/test/observable_map_test.dart, mobx/test/observable_set_test.dart, mobx/test/observable_stream_test.dart, mobx/test/observable_test.dart, mobx/test/observable_value_test.dart, mobx/test/observe_test.dart, mobx/test/reaction_test.dart, mobx/test/reactive_policies_test.dart, mobx/test/spy_test.dart, mobx/test/util.dart, mobx/test/when_test.dart
This will allow expectations in observers to function.
Currently, test expectations written inside of observation handlers don't function. For example, try changing the integer used in the expectation around line 90 in computed_test.dart. Since expectation failures are implemented as a thrown exception, and reaction errors are swallowed unless there is an `onReactionError` handler, tests appear to pass even if the expectations inside of observers fail.
Probably this method call should become standard boilerplate, but I haven't added it to any files other than the one I was looking at while doing a separate PR (coming very shortly). I'm happy to discuss that further.
=> Add a throwReactionErrors setup task.

mobx/lib/src/core/computed.dart, mobx/pubspec.yaml, mobx/test/computed_test.dart
Create a custom `equals` parameter for Computed, like what exists already for Observable.
Currently, Computed uses `==` to determine if the value changed. This creates an option to override that with a different EqualityComparator.
=> Allow a custom equals parameter for Computed.

docs/src/guides/organizing-stores.mdx
Hi, 
I found an error in the documentation. I was trying to replicate the exact code shown, but I was getting an error because I wasn't able to self reference the parent object as an argument to the child. To fix this I've initialized the child inside the parent's constructor, in that scope I was able to call the self reference and carry on coding. It took me a while to get this right as I'm a beginner in Mobx, so I think other beginners might have some trouble with that particular example as well.
Best regards, João Pinto.
=> Fixed self reference while passing parent to child

docs/src/getting-started/index.mdx
Replace 'display1' with 'headline4'
=> docs: Replace deprecated Reference

mobx/lib/src/api/reaction.dart, mobx/lib/src/core/reaction_helper.dart
Fixes reaction with equals, expecting `bool (dynamic, dynamic)`, but should be `bool (T, T)`.
Only relevant if one has following in their `analysis_options.yaml`:
```yaml
analyzer:
strong-mode:
implicit-dynamic: false
```
Currently:
```dart
import 'package:mobx/mobx.dart';
void main() {
final greeting = Observable('Hello World');
reaction<String>( // <--------------------- NOTE: explicit type
(_) => greeting.value,
(msg) => print(msg),
equals: (a, b) => a == b,
);
runInAction(() => greeting.value = 'Hello MobX');
}
```
yields
```
Unhandled exception:
type '(String, String) => bool' is not a subtype of type '(dynamic, dynamic) => bool'
#0      reaction (package:mobx/src/api/reaction.dart:57:17)
#1      main (file:///private/tmp/dart/main.dart:5:3)
#2      _startIsolate.<anonymous closure> …
```
=> match reaction and createReaction signatures

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/pubspec.yaml
Removed support for deprecated APIs and analyzer version for 0.40.x series.
#354 is to support the analyzer lower bound removal.
=> bump analyzer version to >=0.39.1 <0.50.0

mobx_examples/lib/main.reflectable.dart, mobx_examples/lib/todos/todo_list.dart, mobx_examples/lib/todos/todo_list.g.dart, mobx_examples/lib/todos/todo_widgets.dart, mobx_examples/test/todos_test.dart, mobx_examples/test/todos_test.reflectable.dart
Tasks Done - 
- Removed unused observable currentDescription from TodoList.
- Removed onChange callback from TextField in AddTodo Widget.
- Changed TextInputAction to TextInputAction.done
- Updated tests accordingly. All test cases passed.
=> Fixes #529

docs/docs/guides/cheat-sheet.mdx
Fixing doc, the previous one prompt `Getters must be declared without a parameter list.`
=> Fix cheat-sheet doc

docs/docs/examples/github/index.mdx
The import reference for the github package is now 'package:github/github.dart' rather than 'package:github/server.dart'. createGithubClient(...) has also been removed and one is required to just create a GitHub object directly now.
Please see the changelog for v6.0.0 @ https://pub.dev/packages/github/changelog
=> Minor reference update to the 'GitHub Repos' example page

mobx/lib/src/core/context.dart
Currently, spying on the [ReactiveContext] in release builds is prohibited. This makes it impossible to log state-management events for remote diagnostics of user problems in production, which is a great use-case for `@action`s, IMO.
This PR removes the `_isDebugMode` check within the `ReactiveContext.isSpyEnabled`, thus allowing spying in release mode if needed.
=> Enable release mode spying

mobx/lib/src/core/computed.dart, mobx/test/computed_test.dart
Hello,
While working on my app, I noticed that Computed will sometimes not propagate changes in the following simplified use case:
```dart
final emailComputed = Computed<String?>((){
final username = usernameObservable.value;
final user = getUserOrThrow(username);
return user?.email; // can be null
});
```
In the case where callback initially throws, then later recomputes successfully but returns `null`, the computed thinks that nothing changed. This is because there's no caught exception and the value before and after are both null. So it doesn't propagate changes, and any further derivations still think the computed has a caught error
This pull request fixes the bug and ensures that computed with nullable values will propagate changes after errors correctly. Thanks for your time!
=> Bug fix for Computed with nullable values

mobx/lib/src/api/async/observable_stream.dart, mobx/lib/src/api/observable_collections.dart, mobx/test/autorun_test.dart, mobx/test/computed_test.dart, mobx/test/observable_list_test.dart, mobx/test/observable_stream_test.dart, mobx/test/observable_test.dart, mobx_codegen/lib/src/type_names.dart
Hello! 
This PR addresses a TODO in ObservableStream where its observable values (valueType, data, status) are not updated if they are not observed by MobX, even if the underlying stream is emitting events already because `listen()` was called. 
For example:
```dart
final stream = ObservableStream(sourceStream);
final sub = stream.listen(null); // stream starts running
// ...later
print(stream.value) // read outside reaction, still prints null even though stream has emitted values
```
As a side effect, it's now possible to listen to a single-subscription stream *and* observe its values in a reaction, at the same time :) Previously, trying to do both would throw. Note that to comply with the single-subscription stream contract, calling `cancel` on the subscription will also stop further …
=> Fix: ObservableStream.listen() should also keep observable values updated

docs/docs/core-concepts.mdx
Make non-nullable instance field ```Action increment``` late in the example.
dart null safety complains if it is not ```late```:  
> "Non-nullable instance field 'toggleAct' must be initialized.\nTry adding an initializer expression, or add a field initializer in this constructor, or mark it 'late'.",
=> Update core concepts docs

docs/docs/api/spy.mdx, mobx/lib/src/api/observable_collections/observable_map.dart
Hello :wave: 
I've noticed that the section about _spying_ in the docs is somewhat incomplete because **mainContext**'s `isSpyEnabled` defaults to false, so if the user bindly copy the samples they won't work.
=> docs: adds context configuration for spies

flutter_mobx/lib/src/observer_widget_mixin.dart
Close https://github.com/mobxjs/mobx.dart/issues/754
=> Provide more debugging context for `setState() or markNeedsBuild() called during build`

mobx/lib/src/api/store.dart, mobx/test/all_tests.dart, mobx/test/store_test.dart, mobx_codegen/lib/src/template/async_action.dart, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/lib/src/template/observable_future.dart, mobx_codegen/lib/src/template/observable_stream.dart, mobx_codegen/lib/src/template/store.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/all_tests.dart, mobx_codegen/test/data/valid_generic_store_output.dart, mobx_codegen/test/data/valid_import_prefixed_output.dart, mobx_codegen/test/data/valid_late_variables_output.dart, mobx_codegen/test/data/valid_output.dart, mobx_codegen/test/data/valid_output_annotation_store_config_has_to_string.dart, mobx_codegen/test/generator_usage_test.g.dart, mobx_codegen/test/store_with_custom_context.dart, mobx_codegen/test/store_with_custom_context.g.dart, mobx_codegen/test/templates_test.dart
close https://github.com/mobxjs/mobx.dart/issues/718
```dart
class CustomContextStore = _CustomContextStore with _$CustomContextStore;
final ReactiveContext customContext = ReactiveContext();
abstract class _CustomContextStore with Store {
@observable
late String name;
@override
ReactiveContext get context => customContext;
}
```
```dart
mixin _$CustomContextStore on _CustomContextStore, Store {
late final _$nameAtom =
Atom(name: '_CustomContextStore.name', context: context);
@override
String get name {
_$nameAtom.reportRead();
return super.name;
}
@override
set name(String value) {
_$nameAtom.reportWrite(value, super.name, () {
super.name = value;
});
}
@override
String toString() {
return '''
name: ${name}
''';
}
}
```
=> Feat: Allow use custom context

mobx/CHANGELOG.md, mobx/lib/mobx.dart, mobx/lib/src/api/extensions.dart, mobx/lib/src/api/extensions/primitive_types_extensions.dart, mobx/lib/src/core.dart, mobx/lib/src/core/typedefs.dart, mobx/pubspec.yaml, mobx/test/extensions/primitive_types_extensions_test.dart
Dear MobX maintainers, I created some extensions to make a code more concise. I hope you find them useful.
1. Type aliases for primitive types.
So instead of `Observable<int>` you can now write `ObservableInt`.
But it uses the Dart 2.13 feature "type aliases", so I bumped sdk constraints in pubspec to min 2.13
2. `asObservable()` extensions for primitive types. Now you can easily convert literals to observables like:
```dart
var name = ''.asObservable(); // infers ObservableString
var counter = 0.asObservable(); // infers ObservableInt
```
3. `toggle()` method for ObservableBool. Lets you toggle the internal value of ObservableBool
```dart
var lights = true.asObservable();
lights.toggle(); // now it has a value of false
```
=> Observable extensions

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/lib/src/template/store_file.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/valid_output_annotation_store_config_has_to_string.dart
Recommended rules from the `lints` package now include the `no_leading_underscores_for_local_identifiers` rule
The default generated store code with actions breaks this rule, causing the linter to complain
Add the rule to the ignore_for_file part of the template, to pacify the analyzer
Fixes #816
=> Add no_leading_underscores rule to ignore_for_file in mobx_codegen

mobx/CHANGELOG.md, mobx/lib/mobx.dart, mobx/lib/src/api/async/async_action.dart, mobx/pubspec.yaml, mobx/test/spy_test.dart
revert #784 
According to the [docs](https://mobx.js.org/actions.html#asynchronous-actions), the 2.0.7+2 seems to be working correctly.
https://github.com/mobxjs/mobx/discussions/3144
resolve #834
resolve #836
resolve #840
---
=> fix: revert #784

flutter_mobx/CHANGELOG.md, flutter_mobx/lib/flutter_mobx.dart, flutter_mobx/pubspec.yaml, mobx/CHANGELOG.md, mobx/lib/mobx.dart, mobx/pubspec.yaml, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/mobx_codegen.dart, mobx_codegen/pubspec.yaml
pub.dev recently changed the logic for showing the View/report issues link 
---
=> add issue_tracker links to pubspec

mobx/CHANGELOG.md, mobx/lib/src/core.dart, mobx/lib/src/core/atom.dart, mobx/lib/src/core/computed.dart, mobx/lib/src/core/context.dart, mobx/lib/src/core/reaction.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/reaction_test.dart
Dart 2.19 doesn't delegate inaccessible private names to noSuchMethod.
https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2190
https://github.com/dart-lang/language/issues/2020
https://github.com/dart-lang/sdk/issues/49687
https://github.com/dart-lang/site-www/issues/4263
https://github.com/mobxjs/mobx.dart/blob/master/mobx/test/observable_test.dart
The test fails on dart 2.19.
https://github.com/mobxjs/mobx.dart/actions/runs/3262020308/jobs/5359681093
---
=> test: fix tests in dart 2.19

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/type_names.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml
=> update analyzer version to `>=4.4.0 <6.0.0`

mobx/test/action_test.dart
Signed-off-by: Minsu Lee <amond@amond.net>
https://github.com/mobxjs/mobx/blob/63698d0681988194bac5fc01851882b417b35f18/packages/mobx/__tests__/v5/base/action.js#L4
---
=> test: action should wrap in transaction

docs/docs/examples/github/index.mdx
GitHub with capitalized h instead of Github with lowercased h
=> chore: typo

.github/workflows/build.yml, mobx/CHANGELOG.md, mobx/lib/mobx.dart, mobx/lib/src/api/annotations.dart, mobx/lib/src/core.dart, mobx/lib/src/core/atom_extensions.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/annotations_test.dart, mobx/test/atom_extensions_test.dart, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/store_class_visitor.dart, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/generator_usage_test.dart, mobx_codegen/test/generator_usage_test.g.dart
Allows a reaction to be fired even if the value hasn't changed. 
Adds custom equals for creating observables.
#844 
fix https://github.com/mobxjs/mobx.dart/issues/903
---
=> feat: Adds custom `equals` for creating observables.

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/template/util.dart, mobx_codegen/lib/src/type_names.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/valid_output_annotation_store_config_has_to_string.dart, mobx_codegen/test/util_test.dart
Fixes #928
Fixes #929
Fixes #930
---
=> feat: require `analyzer: ^5.12.0`

flutter_mobx/CHANGELOG.md, flutter_mobx/lib/src/multi_reaction_builder.dart, flutter_mobx/lib/src/reaction_builder.dart, flutter_mobx/pubspec.yaml, flutter_mobx/test/all_tests.dart, flutter_mobx/test/multi_reaction_builder_test.dart, flutter_mobx/test/reaction_builder_test.dart
Merges multiple `ReactionBuilder` widgets into one widget tree.
`MultiReactionBuilder` improves the readability and eliminates the need to nest multiple `ReactionBuilder`s.
By using `MultiReactionBuilder` we can go from:
```dart
ReactionBuilder(
builder: (context) {},
child: ReactionBuilder(
builder: (context) {},
child: ReactionBuilder(
builder: (context) {},
child: ChildA(),
),
),
)
```
to:
```dart
MultiReactionBuilder(
builders: [
ReactionBuilder(
builder: (context) {},
),
ReactionBuilder(
builder: (context) {},
),
ReactionBuilder(
builder: (context) {},
),
],
child: ChildA(),
)
```
`MultiReactionBuilder` converts the `ReactionBuilder` list into a tree of nested `ReactionBuilder` widgets.
As a result, the only advantage of using `MultiReactionBuilder` is improved readability due to the …
=> feat: add `MultiReactionBuilder` widget

mobx/CHANGELOG.md, mobx/lib/src/api/observable_collections/observable_list.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/observable_list_test.dart
This PR Fixes issue #941 .
---
=> 🐛 Fixes issue in ObservableList while using Iterables.

flutter_mobx/CHANGELOG.md, flutter_mobx/lib/src/observer.dart, flutter_mobx/lib/version.dart, flutter_mobx/pubspec.yaml, flutter_mobx/test/flutter_mobx_test.dart
I already did a PR https://github.com/mobxjs/mobx.dart/pull/909 but I accidentally deleted the forked repo.
So I made it again and a little bit better.
Mostly you try to make Observer as small as possible. But sometimes you'll want to exclude the widget subtree from re-render and improve the performance.
Real world examples:
1) You have a colored Container with some heavy widgets inside (like `ListView` with `shrinkWrap: true`).
You want to change the color by Observable, but don't want to rebuild the whole ListView.
2) You have some fancy animation driven by Observable. You want to animate the widget and want to preserve its children from being rebuilt.
I introduce the new `Observer.optimized` which allows you to exclude the `child` branch.
Usage:
```dart
Observer.optimized( …
```
=> Observer.optimized

mobx/CHANGELOG.md, mobx/lib/src/core/atom_extensions.dart, mobx/lib/src/core/observable.dart, mobx/lib/src/utils.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/atom_extensions_test.dart
Following up on pr #844, perform deep equals if value is `Iterable` or `Map`.
---
=> Avoid unnecessary observable notifications of Iterable or Map fields

docs/README.md
It looks like we are using `pnpm` instead of `yarn` to build the docs.
https://github.com/mobxjs/mobx.dart/commit/d7dbbf57074f7db0a63273ccfb99f5ca219f0f28
https://github.com/mobxjs/mobx.dart/blob/1388bbdafca4619f51645ae83190fddd6dd127bf/docs/pnpm-lock.yaml
---
=> docs: use pnpm instead of yarn

docs/docs/guides/mobx-vs-inherited-model.mdx, docs/sidebars.js
> @amondnet you should write a blog post about this on the MobX Website ... this kind of information is useful for general audience as well. Just a recommendation :-)
_Originally posted by @pavanpodila in https://github.com/mobxjs/mobx.dart/discussions/948#discussioncomment-7409420_
---
=> docs: add mobx vs inherited model

docs/docs/api/observable.mdx, mobx/CHANGELOG.md, mobx/lib/src/api/annotations.dart, mobx/lib/src/core/atom_extensions.dart, mobx/lib/src/utils.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/all_tests.dart, mobx/test/atom_extensions_test.dart, mobx/test/utils_test.dart, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml
Make the change in 2.2.3 optional. If you want the use this behavior , modify `@observable` to `@MakeObservable(useDeepEquality: true)`.
Fixes #969
---
=> feat: Adds `useDeepEquality` for creating observables

docs/docs/api/observable.mdx, mobx/CHANGELOG.md, mobx/lib/mobx.dart, mobx/lib/src/api/annotations.dart, mobx/lib/src/core/computed.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/computed_test.dart, mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/store_class_visitor.dart, mobx_codegen/lib/src/template/computed.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/valid_keep_alive_computed_input.dart, mobx_codegen/test/data/valid_keep_alive_computed_output.dart, mobx_codegen/test/generator_usage_test.dart, mobx_codegen/test/generator_usage_test.g.dart, mobx_codegen/test/mobx_codegen_test.dart
This avoids suspending computed values when they are not being observed by anything (see the above explanation). Can potentially create memory leaks.
Fixes #975 
---
=> feat: add keepAlive to Computed

melos.yaml, pubspec.yaml
Add mobx_lint_flutter_test package to melos.yaml
update melos dev dependency to version 5.2.1
=> build: melos

mobx_examples/lib/dice/dice_widgets.dart
=> fixed example error

README.md, translation/ja-JP/README.md, translation/ko-KR/README.md, translation/pt-BR/README.md, translation/zh-CN/README.md
=> docs: add Korean README

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/type_names.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml
=> fixing analysis errors

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/type_names.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/with_extension_input.dart, mobx_codegen/test/data/with_extension_output.dart, mobx_codegen/test/mobx_codegen_test.dart
=> fix: error with code generation when file has unnamed extension

mobx/CHANGELOG.md, mobx/lib/src/api/reaction.dart, mobx/lib/src/core/reaction_helper.dart, mobx/lib/version.dart, mobx/pubspec.yaml, mobx/test/autorun_test.dart, mobx/test/reaction_test.dart
Add `scheduler` to `reaction` and `autorun` to allow customizing the scheduler used to schedule the reaction.
https://mobx.js.org/reactions.html#scheduler-_autorun-reaction_
---
=> feat: add scheduler option to autorun and reaction

docs/docs/api/observers.mdx, docs/pnpm-lock.yaml, flutter_mobx/CHANGELOG.md, flutter_mobx/lib/src/observer.dart, flutter_mobx/lib/version.dart, flutter_mobx/pubspec.yaml, flutter_mobx/test/flutter_mobx_test.dart, mobx_codegen/analysis_options.yaml, mobx_codegen/test/generator_usage_test.dart, pubspec.yaml
I fixed Observer.withBuiltChild constructor.
I removed runtime asserts and unneeded nullables. So now it's neat.
I also added an example to the docs.
---
=> withBuildChild fix

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/store_class_visitor.dart, mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/lib/src/template/util.dart, mobx_codegen/lib/src/type_names.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/data/invalid_action_multiple_output.txt, mobx_codegen/test/store_class_visitor_test.dart, mobx_codegen/test/test_utils.dart, mobx_codegen/test/util_test.dart
This PR updates `mobx_codegen` to support the latest `build` and `analyzer` packages, including:
- `analyzer: 7.7.0`
- `build: 3.0.0`
- `source_gen: 3.0.0`
- `build_test: 3.3.0`
For downstream consumers with custom codegen, the version bump will allow them to migrate their own code generators away from the recently deprecated element API in `package:analyzer`. I've also done the conversion for this package, so the cut-over to analyzer 8.0.0 (which fully removes the deprecated API) should be trivial.
Note that while analyzer 8.0.0 has been released, the latest `source_gen` does not yet support it, so this is the latest analyzer version we can upgrade to.
Fixes #1049, fixes #1039.
---
=> Update codegen to use new Element2 API from analyzer >= 7.4.0

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/src/mobx_codegen_base.dart, mobx_codegen/lib/src/store_class_visitor.dart, mobx_codegen/lib/src/template/method_override.dart, mobx_codegen/lib/src/template/observable.dart, mobx_codegen/lib/src/template/util.dart, mobx_codegen/lib/src/type_names.dart, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml, mobx_codegen/test/store_class_visitor_test.dart, mobx_codegen/test/util_test.dart, mobx_examples/lib/clock/clock.dart
This PR updates `mobx_codegen` to use `analyzer: '>=7.4.0 < 9.0.0'`, and also upgrades some related packages. `analyzer >= 8.0.0` removes the old `Element` v1 API, and deprecates the v2 names (e.g. `ClassElement2`).
~This PR also resolves associated deprecations, and removes all deprecation ignore comments except for one, which is unrelated to this change as far as I can tell.~
Deprecation changes have been reverted, see discussion below.
---
=> Update analyzer to >=7.4.0 <9.0.0 and bump related packages

mobx_codegen/CHANGELOG.md, mobx_codegen/lib/version.dart, mobx_codegen/pubspec.yaml
Fixes #1053.
This PR drops `build_resolvers` as a dependency, since we don't import it. See the linked issue above for context. Dropping this dependency allows us to support `build_runner: 2.8.0` without dropping support for any earlier `build_runner` versions.
---
=> Drop unused build_resolvers dependency
